Host github.com
   HostName github.com
   User git
   IdentityFile ~/.ssh/id_ed25519

Host minhdh.github.com
   HostName github.com
   User git
   IdentityFile ~/.ssh/id_ed25519_minhdh

Host hisoft.github.com
   HostName github.com
   User git
   IdentityFile ~/.ssh/id_ed25519_hisoft

Host mhc
   HostName ssh.minhhoccode111.com
   User mhc
   Port 2222
   IdentityFile ~/.ssh/id_ed25519
